#!/usr/bin/env python
# encoding: utf8
# vim: set sts=4 sw=4 et:

from __future__ import print_function, unicode_literals
import os
import sys
import logging


logging.basicConfig(level=logging.DEBUG, format='%(asctime)s: %(message)s')
logger = logging.getLogger(__name__)


def main():
    logger.debug("Hello %s", "world!")
#    for line in sys.stdin:
#        logger.debug(line)
    

if '__main__' == __name__:
    main()

