set t_Co=256
set et
set ts=4
set sw=4
set ai
set rnu
set nu
inoremap <c-u> <esc>viwUea
let mapleader=","
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
inoremap jk <esc>
inoremap <esc> <nop>

filetype plugin indent on
syntax on

let g:solarized_termcolors=256
set background=dark
colorscheme solarized
