set t_Co=256
set et
set sts=4
set sw=4
set ai
set rnu
set nu
set modelines=5
set modeline
inoremap <c-u> <esc>viwUea
let mapleader=","
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
inoremap jk <esc>
inoremap <esc> <nop>

filetype plugin indent on
syntax on

"let g:solarized_termcolors=256
set background=dark
colorscheme solarized

if has("autocmd")
  augroup templates
    au!
    autocmd BufNewFile *.sh 0r ~/.vim/templates/shell
    autocmd BufNewFile *.py 0r ~/.vim/templates/python
    autocmd BufNewFile *.py /Hello
    autocmd BufNewFile *.py :normal V
  augroup end
  augroup rst_ft
    au!
    autocmd BufNewFile,BufRead *.txt set syntax=rst
  augroup END
endif

